# Jekyll의 설정은 이곳에 기본적으로 저장된다.
url: https://nachiketa3299.github.io

collections:
  authors:
 # 콜렉션에 들어갈 문서들은 루트에 있는_*콜렉션 이름*폴더에 들어가게된다.
      output: true
      # 기본적으로 콜렉션은 아무 페이지도 출력하지 않는다. 이 경우 우리는 각각의 저자가 그들 자신의 페이지를 갖도록 원하므로, 콜렉션 설정을 바꾼다. 이게 true로 설정되어 있으면 아웃풋 페이지에 author.url로 링크를 걸 수 있다.

# Jekyll은 사이트 환경설정에 변수들의 기본값을 지정하는 방법을 제공하기 때문에, 새 포스트나 페이지를 추가할 때마다 이러한 환경설정을 반복하지 않아도 된다. 그러기 위해선, 프로젝트의 루트 디렉토리에 있는 _config.yml 파일에 default라는 키를 사용하여 사이트 전체에 사용되는 기본값을 정의할 수 있다.
# defaults 키에 여러 쌍의 범위/값(scope/values)를 배열로 입력할 수 있어서, 특정 경로의 파일이나 파일 종류에 사용되어야 하는 디폴트 값을 정의할 수 있다.
defaults:
  - scope:
      path: "" # 여기서 empty string을 적으면, 프로젝트의 모든 파일임을 의미한다.
      type: "authors" # 프로젝트의 모든 파일 중, 타입이 author인 경우에만 설정을 적용한다. (type의 값으로는 pages, posts, drafts 또는 사이트 내 컬렉션 이름을 적용할 수 있다. scope/vaue쌍 생성시 type은 선택사항이지만, path는 반드시 정의해야 한다.)
    values:
      layout: "author"
      # "authors"라는 이름의 컬렉션 안에는 layout이 "author"로 설정된다.
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag